import { useState } from "react";
import Head from "next/head";
import type { NextPage } from "next";
import { ToastContainer } from "react-toastify";
import Navbar from "../components/Navbar";
import SearchBar from "../components/SearchBar";
import { Coordinates } from "../common/interfaces";
import Forecast from "../components/Forecast";

const Home: NextPage = () => {
  const [coordinates, setCoordinates] = useState<Coordinates>();
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ToastContainer />
      <Navbar />
      <SearchBar setCoordinates={setCoordinates} />
      {coordinates && <Forecast coordinates={coordinates} />}
    </div>
  );
};

export default Home;
